# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Vowpal Wabbit
description: >- # this means to ignore newlines until "baseurl:"
  Vowpal Wabbit provides a fast, flexible, online, and active learning solution
  that empowers you to solve complex interactive machine learning problems.
# baseurl: "/vowpalwabbit.github.io" # the subpath of your site, e.g. /blog
url: "https://vowpalwabbit.org" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-scholar

github:
  repository_url: https://github.com/VowpalWabbit/vowpalwabbit.github.io
  jupyter_notebook_source_url: https://github.com/VowpalWabbit/jupyter-notebooks
  jupyter_notebook_url: https://mybinder.org/v2/gh/VowpalWabbit/jupyter-notebooks/master?filepath=

sass:
  style: compact

collections:
  communities:
    output: true
  features:
    output: true
  feature_details:
    output: true
  reinforcement:
    output: true
  supervised:
    output: true
  flexibility:
    output: true
  tutorials:
    output: true
  bibliography:
    output: true
  rlos:
    output: true
  banner:
    output: true
  posts:
    output: true
    permalink: /blog/:title:output_ext

scholar:
  style: ieee
  cite_class: cite_sup
  bibliography_template:  bibtemplate
  details_layout: bib_download.html
  details_link: Get .bib
  bibtex_options:
    parse_names: false
    strip: false
  sort_by: year, month
  order: descending
defaults:
  -
    scope:
      path: "tutorials"
    values:
      layout: "default"
      navgroup: "tutorials"

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - readme.md