# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby
pool:
  vmImage: 'ubuntu-16.04'

pr:
  branches:
    include:
    - source
    exclude:
    - master

trigger:
  branches:
    include:
    - source
    exclude:
    - master

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.4'
    addToPath: true
- script: gem install bundler
- script: bundle install 
- script: jekyll build
- script: htmlproofer ./_site
