# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby
pool:
  vmImage: 'ubuntu-20.04'

pr:
- source

trigger:
- source

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '2.x'
    addToPath: true
- script: gem install bundler
- script: bundle install
- script: bundle exec jekyll build
- script: htmlproofer --http-status-ignore "429" ./_site
