# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby
pool:
  vmImage: 'ubuntu-16.04'

pr:
- master

trigger:
- master

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.x'
    addToPath: true
- script: gem install html-proofer
- script: htmlproofer --http-status-ignore "429" .
